name: Close PRs to main
on:
  pull-request:
    branches: [main]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr close "$PR_URL" --comment "Auto-closing pull request: the main branch of this repo will be auto-clobbered"


